"use client"
import { useEffect, useRef } from "react"
import { useUIStore } from "@/lib/store/ui"
import { useDeleteTransaction } from "../hooks/useDeleteTransaction"
import { formatAmount } from "@/lib/utils"
import type { TxData } from "@/lib/store/ui"

interface TxRowProps {
  tx: TxData
  categoryName?: string
  categoryColor?: string
}

export function TxRow({ tx, categoryName, categoryColor }: TxRowProps) {
  const focusedIds = useUIStore((s) => s.focusedTxIds)
  const clearFocused = useUIStore((s) => s.clearFocusedTxIds)
  const openEdit = useUIStore((s) => s.openEdit)
  const isFocused = focusedIds.includes(tx.id)
  const ref = useRef<HTMLDivElement>(null)
  const deleteTx = useDeleteTransaction()

  useEffect(() => {
    if (!isFocused) return
    ref.current?.scrollIntoView({ behavior: "smooth", block: "center" })
    const t = setTimeout(clearFocused, 2800)
    return () => clearTimeout(t)
  }, [isFocused, clearFocused])

  const isIncome = tx.type === "income"
  const date = new Date(tx.date + "T00:00:00")
  const formatted = date.toLocaleDateString("en-US", { month: "short", day: "numeric" })

  return (
    <div
      ref={ref}
      data-testid="tx-row"
      className={`group flex items-center gap-3 py-3.5 px-4 rounded-[var(--radius-md)] bg-[var(--surface)] transition-all duration-150
        hover:shadow-md hover:-translate-y-px cursor-default
        ${isFocused ? "shadow-md ring-2 ring-[var(--accent)]/40" : "shadow-sm"}
        ${isIncome ? "border-l-[3px] border-l-[var(--income)]" : ""}`}
    >
      {/* Date — desktop only */}
      <span className="hidden sm:block font-mono text-xs text-[var(--text-2)] w-[88px] shrink-0">{formatted}</span>

      {/* Merchant + inline meta on mobile */}
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-1.5">
          <p className="font-serif text-[17px] text-[var(--text)] truncate">
            {tx.merchant ?? "—"}
          </p>
          {tx.recurring_rule_id && (
            <span className="text-xs opacity-50 shrink-0" title="Auto-generated by recurring rule">↻</span>
          )}
        </div>
        <div className="flex items-center gap-2 mt-0.5 flex-wrap">
          <span className="sm:hidden font-mono text-[10px] text-[var(--text-3)]">{formatted}</span>
          {categoryName && (
            <span className="sm:hidden inline-flex items-center gap-1 text-[11px] text-[var(--text-2)] lowercase tracking-[0.04em]">
              <span className="w-1.5 h-1.5 rounded-full shrink-0"
                style={{ backgroundColor: categoryColor ?? "var(--text-3)" }} />
              {categoryName}
            </span>
          )}
          {tx.notes && (
            <p className="text-[11px] text-[var(--text-3)] truncate">{tx.notes}</p>
          )}
        </div>
      </div>

      {/* Category — desktop only */}
      <div className="hidden sm:flex items-center w-[140px] shrink-0">
        {categoryName && (
          <span className="inline-flex items-center gap-1.5 text-[11px] text-[var(--text)] lowercase tracking-[0.04em]">
            <span className="w-1.5 h-1.5 rounded-full shrink-0"
              style={{ backgroundColor: categoryColor ?? "var(--text-3)" }} />
            {categoryName}
          </span>
        )}
      </div>

      {/* Amount */}
      <div className="shrink-0 text-right">
        <span className={`font-mono text-[15px] ${isIncome ? "text-[var(--income)]" : "text-[var(--text)]"}`}>
          <span className="text-[12px] text-[var(--text-3)]">{tx.currency} </span>
          {formatAmount(tx.amount)}
        </span>
      </div>

      {/* Actions */}
      <div className="flex items-center gap-0.5 opacity-100 md:opacity-0 md:group-hover:opacity-100 md:group-focus-within:opacity-100 transition-opacity duration-100 shrink-0">
        <button
          type="button"
          data-testid="tx-edit"
          onClick={() => openEdit(tx)}
          className="p-2 text-[var(--text-3)] hover:text-[var(--text)] hover:bg-[var(--rule)] rounded text-sm leading-none"
          aria-label={`Edit ${tx.merchant ?? "transaction"}`}>
          ✎
        </button>
        <button
          type="button"
          data-testid="tx-delete"
          onClick={() => deleteTx.mutate(tx)}
          disabled={deleteTx.isPending}
          className="p-2 text-[var(--text-3)] hover:text-[var(--danger)] hover:bg-[var(--rule)] rounded text-sm leading-none"
          aria-label={`Delete ${tx.merchant ?? "transaction"}`}>
          ×
        </button>
      </div>
    </div>
  )
}
