apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yomochi.fullname" . }}
  labels:
    {{- include "yomochi.labels" . | nindent 4 }}
data:
  LOG_FORMAT: {{ .Values.env.LOG_FORMAT | quote }}
  OTEL_ENABLED: {{ .Values.env.OTEL_ENABLED | quote }}
  {{- if .Values.env.OTEL_EXPORTER_OTLP_ENDPOINT }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.env.OTEL_EXPORTER_OTLP_ENDPOINT | quote }}
  {{- end }}
  {{- if .Values.env.KAFKA_BOOTSTRAP_SERVERS }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.env.KAFKA_BOOTSTRAP_SERVERS | quote }}
  {{- end }}
  {{- if .Values.env.COOKIE_SECURE }}
  COOKIE_SECURE: {{ .Values.env.COOKIE_SECURE | quote }}
  {{- end }}
