from datetime import date
from typing import Protocol

from app.domain.entities.recurring_rule import RecurringRule
from app.domain.value_objects.ids import RecurringRuleId, UserId


class RecurringRuleRepository(Protocol):
    async def save(self, rule: RecurringRule) -> None: ...
    async def get(self, id_: RecurringRuleId, user_id: UserId) -> RecurringRule | None: ...
    async def list_(self, user_id: UserId) -> list[RecurringRule]: ...
    async def delete(self, id_: RecurringRuleId, user_id: UserId) -> None: ...
    async def fetch_due_for_update(self, as_of: date, limit: int) -> list[RecurringRule]: ...
