from typing import Protocol


class ConsumerIdempotencyStore(Protocol):
    async def is_processed(self, event_id: str) -> bool: ...
    async def mark_processed(self, event_id: str, ttl_seconds: int) -> None: ...
    async def increment_failures(self, event_id: str) -> int: ...
